// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqpmkqudldcswpbizboj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxcG1rcXVkbGRjc3dwYml6Ym9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODA4NDQsImV4cCI6MjA1OTA1Njg0NH0.tMAXO85mc_q2jGG449kAYcGUfyAwna_W20rgyUfnqes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);